DC-3353 - Get message for secure-message-frontend
hmrc/secure-message-stub pull request #59
Opened 2021-05-11 12:55 UTC by jim-collins

2021-05-11 13:35 UTC, elabeca approved these changes

2021-05-11 13:39 UTC, muralishub approved these changes

2021-05-11 13:45 UTC, muralishub requested changes

2021-05-11 13:45 UTC, muralishub commented on README.md
> +4. */secure-message-stub/messages/:id* to view a specific letter
We should make this to work for conversation or letter

2021-05-11 13:47 UTC, alexflav23 approved these changes

2021-05-11 14:21 UTC, muralishub approved these changes

2021-05-12 10:14 UTC, chandankumarray approved these changes

2021-05-12 10:15 UTC, merged